name: Run e-CAPS

on:
  schedule:
    - cron: "0 23 * * 0" # Runs at 23:00 UTC every Sunday
  workflow_dispatch:
    inputs:
      name:
        description: "Enter Name/Callsign"
        required: true
        default: "arc"
        type: string

jobs:
  run-selenium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          NAME: ${{ github.event.inputs.name || 'arc' }}
        run: |
          python script.py --name "$NAME"
