name: Run e-CAPS

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter Name/Callsign"
        required: True
        default: arc

jobs:
  run-selenium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          pip install -r requirements.txt
      - name: Run script
        run: |
          python script.py --name "${{ github.event.inputs.name }}"
